a = "!! umaima ,tayyaba , jameela!!"
print (a)
print (len(a))
print (a.upper())
print (a.lower())
print (a.rstrip("!"))
print (a.replace("umaima","tayyaba"))
print (a.split(" "))
print (a.count("!"))
print (a.endswith("!"))
print (a.find("umaima"))
print (a.index("!!"))
print (a.isalnum())
print (a.isalpha())
print (a.isprintable())
print (a.islower())
print (a.isspace())
print (a.istitle())
print (a.isupper())
print (a.capitalize())
print (a.title())
print(a.swapcase())
print (a.center(50, "*"))