print("hello")
name = input("please enter your name:")
name = str(name)
item  =input("enter the price of the item:")
item = float(item)
quantity= input("how much do you wanna buy?:")
quantity = float (quantity)
print ("your total bill is:", quantity * item)
print ("hello, {}! You have bought {} of {}".format(name, quantity, item))