print("hello")
name = input("please enter your name:")
name = str(name)
price  =input("enter the price of each book:")
price = float(price))
quantity= input("how many books are you buying?:")
quantity = float (quantity)
print ("your total bill is:", quantity * price )
print ("hello, {}! You have bought {} of {}".format(name, quantity, price))